default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: railway
  username: postgres
  password: cV0ZDmQIHOoaGdRYrdl6
  host: containers-us-west-47.railway.app
  port: 6639
  pool: 5